apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: awpms/image-base
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8081
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/info
              port: 8081
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 10
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /jars
              name: myjars
            - mountPath: /imgdata
              name: imgdata
          envFrom:
            - configMapRef:
                name: generic-config-map
            - configMapRef:
                name: api-config-map
          env:
            - name: APP_JAR
              value: /jars/api-0.0.1-SNAPSHOT.jar
      volumes:
        - name: myjars
          hostPath:
            path: /hostrepos/imglib/imagelib-docker/jars
            type: Directory
        - name: imgdata
          hostPath:
            path: /hostrepos/imgdata
            type: Directory
