apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekasrv
  labels:
    app: eurekasrv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eurekasrv
  template:
    metadata:
      labels:
        app: eurekasrv
    spec:
      containers:
        - name: eurekasrv
          image: awpms/image-base
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8761
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/info
              port: 8761
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 10
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8761
          volumeMounts:
            - mountPath: /jars
              name: myjars
          env:
            - name: APP_JAR
              value: /jars/discovery-0.0.1-SNAPSHOT.jar
            - name: CONFIG_SERVER
              value: http://configserver:8082
            - name: USER_JVM_OPT
              value: "-Dspring.profiles.active=docker"
      volumes:
        - name: myjars
          hostPath:
            path: /hostrepos/imagelib/docker/jars
            type: Directory
            
